

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  UNKNOWN = 'UNKNOWN',
}

export interface GroundingSource {
  uri: string;
  title: string;
}

export interface GraphNode {
  id: string;
  label: string;
  type: string;
}

export interface GraphEdge {
  source: string;
  target: string;
  label: string;
}

export interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

export interface TransparencyReportData {
  process: string[];
  limitations: string[];
  disclaimer: string;
}

export interface AnalysisResult {
  riskLevel: RiskLevel;
  summary: string;
  // FIX: Allow insights to be complex objects, not just strings, to match component logic.
  insights?: (string | { [key: string]: any })[];
  sources: GroundingSource[];
  graphData?: GraphData;
  originalContent: string;
  originalType: 'text' | 'url' | 'image' | 'document';
  // New fields for detailed analysis
  credibilityScore?: number;
  // FIX: Allow keyHighlights to be complex objects, not just strings, to match component logic.
  keyHighlights?: (string | { [key: string]: any })[];
  metadata?: Record<string, any>;
  imageDescriptions?: string[];
  // FIX: Allow nextSuggestions to be complex objects, not just strings, to match component logic. This resolves the compile error in DeepDive.tsx.
  nextSuggestions?: (string | { [key: string]: any })[];
  tone?: string;
  isFromCache?: boolean;
  sourceFileName?: string;
  transparencyReport?: TransparencyReportData;
  // New NLP fields
  language?: string;
  sentiment?: string;
}

export interface EducationalItem {
  title: string;
  content: string;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

export interface HistoryItem {
  id: string;
  timestamp: string;
  result: AnalysisResult;
  chatHistory: ChatMessage[];
}


export const educationalContent: EducationalItem[] = [
  {
    title: "What's new in this version?",
    content: "We've upgraded Trust AI with Deep Dive analysis for documents (PDFs, text files, and more). Uncover metadata, key entities, and even analyze images within your documents. The new follow-up assistant is more context-aware, helping you explore topics in greater detail.",
  },
  {
    title: "How is Credibility Scored?",
    content: "This tool leverages ensemble machine learning algorithms, which are exceptionally well-suited for credibility scoring. These methods handle complex, non-linear data patterns to achieve high predictive accuracy. Specifically, Gradient Boosting models (like XGBoost and LightGBM) and Random Forests are industry-leading choices. Gradient Boosting works by sequentially building a series of predictive models, where each new model corrects the errors of its predecessor. Random Forests operate by constructing numerous decision trees and combining their outputs. This approach reduces errors and makes the final prediction more robust and reliable for the nuanced challenge of assessing content credibility.",
  },
  {
    title: "Check the Source",
    content: "Investigate the website, author, and publisher. Are they reputable? Do they have a history of accuracy? Look for an 'About Us' page and contact information. Be wary of unfamiliar sources or those with a clear agenda.",
  },
  {
    title: "Verify Websites and URLs",
    content: "Before trusting a website, check its domain. Does it look professional? Look for a padlock icon in the address bar (HTTPS). Be cautious of URLs that mimic well-known sites but have slight misspellings. Use WHOIS tools to check how long a domain has been registered; newer domains can be a sign of a less established source."
  },
  {
    title: "Look for Evidence and Corroboration",
    content: "Credible stories are backed by evidence, such as quotes from experts, official data, or documents. Check if other reputable news outlets are reporting the same story. A lack of coverage elsewhere can be a major red flag.",
  },
  {
    title: "Beware of Emotional Language",
    content: "Misinformation often uses sensationalist or emotionally charged language to provoke a strong reaction (fear, anger, excitement). Be skeptical of headlines with excessive capitalization, exclamation points, or dramatic claims.",
  },
  {
    title: "Verify Images and Videos",
    content: "Images and videos can be taken out of context, edited, or even generated by AI. Use reverse image search tools (like Google Images) to see where an image originated and if it has been used in other contexts.",
  },
  {
    title: "Identify Author Bias",
    content: "Consider whether the author or publication has a particular bias. Does the story present a balanced view, or does it seem to be pushing a specific agenda? Look for objective language versus opinionated or persuasive wording."
  }
];